spring.application.name=crud

# Configuración de Correo (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ramsespaolotorneronarvaez@gmail.com
spring.mail.password=xxqfxetyashehypx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mysql://localhost/black_code?serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*


spring.jpa.hibernate.ddl-auto=update
server.servlet.session.timeout=30m
